using System;
using System.ComponentModel.DataAnnotations;

namespace server.Models
{
    public class Page
    {
        [Key]
        public int Id { get; set; }  // Automatically generated by the database.
        
        [MaxLength(100)]
        public string Title { get; set; } = "New Page";

        [Required]
        [MaxLength(200)]
        public string Slug { get; set; }

        public string Content { get; set; } = string.Empty;

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        public DateTime? UpdatedAt { get; set; }

        public Page()
        {
            Slug ??= Guid.NewGuid().ToString();  // Assign a unique identifier if the Slug is empty.
        }
    }
}
